services:
  redis:
    image: redis:7
    container_name: deLink-redis
    ports:
      - "6379:6379"
    restart: unless-stopped

  postgres:
    image: postgres:17
    container_name: deLink-postgres
    environment:
      - POSTGRES_USER=${DELINK_DB_USERNAME}
      - POSTGRES_PASSWORD=${DELINK_DB_PASSWORD}
      - POSTGRES_DB=${DELINK_DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

  main-service:
    build: .
    container_name: deLink-main-service
    ports:
      - "8081:8081"
    env_file:
      - ./.env
    depends_on:
      - postgres
      - redis
    volumes:
      - ./logs:/app/logs

volumes:
  postgres-data: